spring:
  application:
    name: coursesPaginatedCrud
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
